export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCT_BY_CATEGORY';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_FOR_MEN = 'GET_PRODUCTS_FOR_MEN';
export const GET_PRODUCTS_FOR_WOMEN = 'GET_PRODUCTS_FOR_WOMEN';
export const GET_PRODUCTS_FOR_CHILDREN = 'GET_PRODUCTS_FOR_CHILDREN';